name: ci build | Dev Branch

on:
  push:
    branches: [ dev ]

jobs:             
  build:
    name: build
    runs-on: ubuntu-latest
    env:
      HUSKY: 0
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Build
        run: |
          npm install
          npm run build
